import logging
import os
import json
from typing import Optional
import httpx
from app.core.config import settings

logger = logging.getLogger("vulnra.guardian.fixer")


class GuardianFixer:
    def __init__(self):
        self.api_key = os.environ.get("GEMINI_API_KEY", "")
        self.model = settings.guardian_gemini_model
        self.lobster_trap_url = settings.lobster_trap_url.rstrip("/")
        self.lobster_trap_enabled = settings.lobster_trap_enabled

    async def generate_policy(self, evaluation: dict) -> dict:
        findings = evaluation.get("findings", [])
        if not findings:
            return {
                "policy": None,
                "policy_yaml": "# No vulnerabilities found — no policy needed.\n",
                "deployed": False,
                "rule_count": 0,
                "message": "No policy needed.",
            }

        if not self.api_key:
            return self._rule_policy(findings)

        try:
            return await self._geminid_policy(findings)
        except Exception as exc:
            logger.error(f"Gemini policy generation failed: {exc}")
            return self._rule_policy(findings)

    def _rule_policy(self, findings: list[dict]) -> dict:
        import yaml

        high_sev = [f for f in findings if f.get("severity") in ("CRITICAL", "HIGH")]
        medium_sev = [f for f in findings if f.get("severity") == "MEDIUM"]
        low_sev = [f for f in findings if f.get("severity") == "LOW"]

        rules = []
        for f in high_sev:
            vid = f.get("vector_id", "unknown")
            owasp = f.get("owasp_category", "LLM01")
            rules.append({
                "name": f"block_{vid}",
                "description": f"Block {f.get('category', vid)} attacks",
                "priority": "CRITICAL",
                "match": {
                    "intent": [vid.replace("_", "_")],
                    "min_risk_score": 0.7,
                },
                "action": "DENY",
            })
            rules.append({
                "name": f"log_{vid}",
                "description": f"Log all {f.get('category', vid)} attempts for review",
                "priority": "HIGH",
                "match": {
                    "intent": [vid.replace("_", "_")],
                    "min_risk_score": 0.3,
                },
                "action": "LOG",
            })

        for f in medium_sev:
            vid = f.get("vector_id", "unknown")
            rules.append({
                "name": f"quarantine_{vid}",
                "description": f"Quarantine {f.get('category', vid)} attempts",
                "priority": "MEDIUM",
                "match": {
                    "intent": [vid.replace("_", "_")],
                    "min_risk_score": 0.5,
                },
                "action": "QUARANTINE",
            })

        policy = {
            "api_version": "v1",
            "name": "guardian-auto-policy",
            "description": "Auto-generated by GuardianForge autonomous cycle",
            "default_action": "ALLOW",
            "rules": rules,
        }

        policy_yaml = yaml.dump(policy, default_flow_style=False, sort_keys=False)
        deployed = self._deploy_policy(policy_yaml) if self.lobster_trap_enabled else False

        return {
            "policy": policy,
            "policy_yaml": policy_yaml,
            "deployed": deployed,
            "rule_count": len(rules),
            "message": f"Generated {len(rules)} rules ({len(high_sev)} high, {len(medium_sev)} medium, {len(low_sev)} low)."
        }

    async def _geminid_policy(self, findings: list[dict]) -> dict:
        import yaml

        findings_json = json.dumps(findings, indent=2, default=str)
        prompt = f"""You are a security policy engineer generating Lobster Trap YAML policies.

Based on these evaluation findings, generate a Lobster Trap policy:

{findings_json}

Generate a YAML policy with:
- name: guardian-auto-policy
- default_action: ALLOW
- Rules that block/quarantine/log the attack vectors based on severity
- CRITICAL/HIGH findings → DENY action
- MEDIUM findings → QUARANTINE action
- LOW findings → LOG action

Return ONLY valid YAML, no markdown fences."""

        import google.generativeai as genai
        genai.configure(api_key=self.api_key)
        model = genai.GenerativeModel(self.model)
        response = model.generate_content(prompt)
        raw = response.text.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[-1]
            raw = raw.rsplit("\n", 1)[0]
            if raw.endswith("```"):
                raw = raw[:-3]

        try:
            policy = yaml.safe_load(raw)
        except Exception as exc:
            logger.error(f"Failed to parse Gemini YAML: {exc}")
            return self._rule_policy(findings)

        rule_count = len(policy.get("rules", []))
        policy_yaml = yaml.dump(policy, default_flow_style=False, sort_keys=False)
        deployed = self._deploy_policy(policy_yaml) if self.lobster_trap_enabled else False

        return {
            "policy": policy,
            "policy_yaml": policy_yaml,
            "deployed": deployed,
            "rule_count": rule_count,
            "message": f"Gemini-generated policy with {rule_count} rules."
        }

    def _deploy_policy(self, policy_yaml: str) -> bool:
        if not self.lobster_trap_enabled:
            return False
        try:
            with httpx.Client(timeout=10.0) as client:
                resp = client.post(
                    f"{self.lobster_trap_url}/policies",
                    json={"policy_yaml": policy_yaml},
                )
            if resp.is_success:
                logger.info("GuardianForge policy deployed to Lobster Trap")
                return True
            logger.warning(f"Lobster Trap policy deploy returned {resp.status_code}")
            return False
        except httpx.RequestError as exc:
            logger.warning(f"Lobster Trap unreachable during policy deploy: {exc}")
            return False
